apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-amdnested
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,b3B0aW9ucyBrdm1fYW1kIG5lc3RlZD0x
        filesystem: root
        mode: 0644
        path: /etc/modprobe.d/kvm.conf
        overwrite: true

